# Generated by Django 3.2.5 on 2021-12-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('details', models.TextField()),
                ('author', models.TextField(default='Zaid kamil', max_length=30)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
