# Generated by Django 3.2.5 on 2021-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News List'},
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Zaid kamil', max_length=30),
        ),
    ]
