# Generated by Django 3.2.6 on 2021-12-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
